### ISSUE TITLE
pies2overrides breaks virtualenv

### ISSUE THREAD

**Issue by mgedmin** [timothycrosley/pies#32]
As a side effect of an innocent-seeming `pip install isort` I ended up with a non-functional virtualenv thanks to incomplete copies of standard-library packages (copyreg.py?  configparser.py?) polluting my virtualenv's site-packages directory.  I wasted two or three hours debugging this: https://github.com/pypa/virtualenv/issues/671

Please don't install modules that clash with the standard library into the global namespace.

**Comment by blueyed** [comment]
For reference: when using wheels this will happen currently: #44.
