### ISSUE TITLE
Installs pies2overrides on Python 3!

### ISSUE THREAD

**Issue by blueyed** [timothycrosley/pies#44]
% pip install pies
    Collecting pies==2.6.5
      Using cached pies-2.6.5-py2.py3-none-any.whl
    Collecting enum34 (from pies==2.6.5)
      Using cached enum34-1.0.4.tar.gz
    Collecting pies2overrides (from pies==2.6.5)
      Using cached pies2overrides-2.6.5-py2.py3-none-any.whl
    Collecting ipaddress (from pies2overrides->pies==2.6.5)
      Using cached ipaddress-1.0.7.tar.gz
    Installing collected packages: enum34, ipaddress, pies2overrides, pies
      Running setup.py install for enum34
      Running setup.py install for ipaddress
      Found existing installation: pies 2.6.3
        Uninstalling pies-2.6.3:
          Successfully uninstalled pies-2.6.3
    Successfully installed enum34-1.0.4 ipaddress-1.0.7 pies-2.6.5 pies2overrides-2.6.5

This does not happen for 2.6.3, and causes weird issues, e.g. because of the `reprlib.py` being installed.

**Comment by blueyed** [comment]
This is caused by using the wheel for installation.

Probably the config should not have `universal = 1`, which probably causes the same wheel (with the same dependencies) to be used for Python 2 and 3?

**Comment by ghickman** [comment]
I can confirm that the wheel is install pies2overrides in a python 3 virtualenv.

@blueyed is correct, the `[wheel]` section of setup.cfg is causing this issue. Unfortunately this will require two wheels to be built for each distribution. One using each python major release.

My output (using `mktmpenv`): https://gist.github.com/ghickman/7b20200ad43676acf97e

**Comment by timothycrosley** [comment]
This should be fixed in 2.6.7 which was just released, thank for reporting this issue!

~Timothy
